name: Deploy Sanity Studio

on:
  push:
    paths:
      - 'sanity/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        working-directory: ./sanity
        run: npm install

      - name: Deploy Sanity Studio
        working-directory: ./sanity
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: npx sanity deploy --no-confirm
